
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        Carro5 = new javax.swing.JLabel();
        Carro2 = new javax.swing.JLabel();
        Carro3 = new javax.swing.JLabel();
        Carro4 = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        lblBanderai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        NuevoCarrera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblBandera1 = new javax.swing.JLabel();
        Carro1 = new javax.swing.JLabel();
        Carro6 = new javax.swing.JLabel();
        Carro7 = new javax.swing.JLabel();
        Carro8 = new javax.swing.JLabel();
        Carro9 = new javax.swing.JLabel();
        Carro10 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblLinea.setBackground(new java.awt.Color(153, 255, 153));
        lblLinea.setForeground(new java.awt.Color(51, 255, 102));
        lblLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linea.png"))); // NOI18N

        Carro5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro5.png"))); // NOI18N

        Carro2.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro2.png"))); // NOI18N

        Carro3.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro3.png"))); // NOI18N

        Carro4.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro4.png"))); // NOI18N

        Inicio.setBackground(new java.awt.Color(51, 255, 255));
        Inicio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Inicio.setText("!A CORRER!");
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        lblBanderai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banderainicio.png"))); // NOI18N

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        NuevoCarrera.setBackground(new java.awt.Color(102, 255, 255));
        NuevoCarrera.setText("NUEVA CARRERA");
        NuevoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoCarreraActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("TABLÓN DE RESULTADOS");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("LA CARRERA DEL SIGLO!");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("!Ferrari vs Maserati vs Lotus vs Toyota vs Mercedes vs Porsche vs Honda vs Renault vs Bmw vs Peugeot!");

        lblBandera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandera.png"))); // NOI18N

        Carro1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro1.png"))); // NOI18N

        Carro6.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro6.png"))); // NOI18N

        Carro7.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro7.png"))); // NOI18N

        Carro8.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro8.png"))); // NOI18N

        Carro9.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro9.png"))); // NOI18N

        Carro10.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        Carro10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carro10.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Carro10)
                                .addGap(62, 62, 62)
                                .addComponent(Inicio))
                            .addComponent(Carro3)
                            .addComponent(Carro2)
                            .addComponent(Carro4)
                            .addComponent(Carro1)
                            .addComponent(Carro8)
                            .addComponent(Carro9)
                            .addComponent(Carro5)
                            .addComponent(Carro7)
                            .addComponent(Carro6))
                        .addGap(221, 221, 221)
                        .addComponent(NuevoCarrera)
                        .addGap(41, 41, 41)
                        .addComponent(lblLinea))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBanderai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBandera1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBanderai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NuevoCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(Carro1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Carro10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBandera1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        GUI.txtR.setText("Tiempos de llegada:");
        Carrera.iniciar();
        Inicio.setEnabled(false);
        NuevoCarrera.setEnabled(true);
    }//GEN-LAST:event_InicioActionPerformed

    private void NuevoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoCarreraActionPerformed
        Carrera.reiniciar();
        Carro1.setLocation(Carrera.Carros[0].getCoorX(),Carrera.Carros[0].getCoorY());
        Carro2.setLocation(Carrera.Carros[1].getCoorX(),Carrera.Carros[1].getCoorY());
        Carro3.setLocation(Carrera.Carros[2].getCoorX(),Carrera.Carros[2].getCoorY());
        Carro4.setLocation(Carrera.Carros[3].getCoorX(),Carrera.Carros[3].getCoorY());
        Carro5.setLocation(Carrera.Carros[4].getCoorX(),Carrera.Carros[4].getCoorY());
        Carro6.setLocation(Carrera.Carros[5].getCoorX(),Carrera.Carros[5].getCoorY());
        Carro7.setLocation(Carrera.Carros[6].getCoorX(),Carrera.Carros[6].getCoorY());
        Carro8.setLocation(Carrera.Carros[7].getCoorX(),Carrera.Carros[7].getCoorY());
        Carro9.setLocation(Carrera.Carros[8].getCoorX(),Carrera.Carros[8].getCoorY());
        Carro10.setLocation(Carrera.Carros[9].getCoorX(),Carrera.Carros[9].getCoorY());
        Inicio.setEnabled(true);
        NuevoCarrera.setEnabled(false);
    }//GEN-LAST:event_NuevoCarreraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        NuevoCarrera.setEnabled(false);
        Carrera.registroAutos();
        Carro1.setText(Carrera.Carros[0].getNombre());
        Carro2.setText(Carrera.Carros[1].getNombre());
        Carro3.setText(Carrera.Carros[2].getNombre());
        Carro4.setText(Carrera.Carros[3].getNombre());
        Carro5.setText(Carrera.Carros[4].getNombre());
        Carro6.setText(Carrera.Carros[5].getNombre());
        Carro7.setText(Carrera.Carros[6].getNombre());
        Carro8.setText(Carrera.Carros[7].getNombre());
        Carro9.setText(Carrera.Carros[8].getNombre());
        Carro10.setText(Carrera.Carros[9].getNombre());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Carro1;
    public static javax.swing.JLabel Carro10;
    public static javax.swing.JLabel Carro2;
    public static javax.swing.JLabel Carro3;
    public static javax.swing.JLabel Carro4;
    public static javax.swing.JLabel Carro5;
    public static javax.swing.JLabel Carro6;
    public static javax.swing.JLabel Carro7;
    public static javax.swing.JLabel Carro8;
    public static javax.swing.JLabel Carro9;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton NuevoCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblBandera1;
    public static javax.swing.JLabel lblBanderai;
    public static javax.swing.JLabel lblLinea;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
