/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.Scanner;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


public class votos extends javax.swing.JFrame {

    DefaultTableModel Datos;
    
    
    public votos() {
        initComponents();
        Datos= new DefaultTableModel();
        Datos.addColumn("Enero");
        Datos.addColumn("Febrero");
        Datos.addColumn("Marzo");
        Datos.addColumn("Abril");
        Datos.addColumn("Mayo");
        Datos.addColumn("Junio");
        Datos.addColumn("Julio");
        Datos.addColumn("Agosto");
        Datos.addColumn("Septiembre");
        Datos.addColumn("Octubre");
        Datos.addColumn("Noviembre");
        Datos.addColumn("Diciembre");
        this.tabla.setModel(Datos);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("resultados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String linea =null;
            String linea1=null;
            String[] valores;
            String[] nombres;
            File archivo = new File("BaseDeDatos.csv");
            int ene=0,feb=0,mar=0,abr=0,may=0,jun=0,jul=0,ago=0,sep=0,oct=0,nov=0,dec=0;
        Datos.setRowCount(3);
        
        try {     
            Scanner entrada = new Scanner (archivo);
            linea=entrada.nextLine();
            System.out.println(linea);
            nombres=linea.split(",");
            linea1=entrada.nextLine();
            System.out.println(linea1);
            valores=linea1.split(",");
            
            for(int i=0;i<nombres.length;i++){
                if("01".equals(nombres[i])){
                    ene=Integer.valueOf(valores[i])+ene;
                }
                if("02".equals(nombres[i])){
                    feb=Integer.valueOf(valores[i])+feb;
                }
                if("03".equals(nombres[i])){
                    mar=Integer.valueOf(valores[i])+mar;
                }
                if("04".equals(nombres[i])){
                    abr=Integer.valueOf(valores[i])+abr;
                }
                if("05".equals(nombres[i])){
                    may=Integer.valueOf(valores[i])+may;
                }
                if("06".equals(nombres[i])){
                    jun=Integer.valueOf(valores[i])+jun;
                }
                if("07".equals(nombres[i])){
                    jul=Integer.valueOf(valores[i])+jul;
                }
                if("08".equals(nombres[i])){
                    ago=Integer.valueOf(valores[i])+ago;
                }
                if("09".equals(nombres[i])){
                    sep=Integer.valueOf(valores[i])+sep;
                }
                if("10".equals(nombres[i])){
                    oct=Integer.valueOf(valores[i])+oct;
                }
                if("11".equals(nombres[i])){
                    nov=Integer.valueOf(valores[i])+nov;
                }
                if("12".equals(nombres[i])){
                    dec=Integer.valueOf(valores[i])+dec;
                }
            }
            tabla.setValueAt(String.valueOf(ene), 1, 0);
            tabla.setValueAt(String.valueOf(feb), 1, 1);
            tabla.setValueAt(String.valueOf(mar), 1, 2);
            //Datos.setValueAt(ra, 1, 1);
            //Datos.setValueAt(bl, 1, 2);
            System.out.println(ene);
            System.out.println(feb);
            System.out.println(mar);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(votos.class.getName()).log(Level.SEVERE, null, ex);
        }
        File f = new File("IntentoQuiz.csv");
           
            try{
                FileWriter fw = new FileWriter(f);
                fw.write("Enero,Febrero,Marzo");
                fw.write("\n");
                fw.write(ene+","+feb+","+mar);
                fw.close();
            }catch(Exception ex){
                System.out.println("Error");
            }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
